# name: CD
# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GHCR_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           tags: ghcr.io/${{ github.repository_owner }}/django-app:latest

#       - name: Deploy to Kubernetes
#         run: |
#           # Create a temporary kubeconfig file
#           echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig.yaml

#           # Apply all Kubernetes manifests
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/namespace.yaml
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/secret.yaml
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/configmap.yaml
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/deployment.yaml
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/service.yaml
#           kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/hpa.yaml


name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/django-app:latest 