name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Test connectivity to Postgres with psql before migrating
      - name: Wait for Postgres connection
        run: |
          echo "Waiting for Postgres to become available..."
          for i in {1..20}; do
            if pg_isready -h postgres -U postgres -d test_db; then
              echo "✅ Postgres is ready!"
              break
            fi
            echo "⏳ Waiting for Postgres ($i)..."
            sleep 5
          done

          echo "Testing psql connection..."
          PGPASSWORD=postgres psql -h postgres -U postgres -d test_db -c "SELECT 1;" || (echo "❌ Failed to connect to Postgres" && exit 1)

      - name: Run migrations
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: python manage.py migrate --noinput

      - name: Run tests
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: python manage.py test products